services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=password123
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_DATABASE_PASSWORD=db_password
      - BITNAMI_DEBUG=true
    volumes:
      - '.:/bitnami/'
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=db_password
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mariadb_data:
    driver: local
